MatchingTranslations:
  enabled: false
LiquidTag:
  enabled: false
MissingTemplate:
  enabled: false
UndefinedObject:
  enabled: false
  exclude_snippets: true
SchemaJsonFormat:
  enabled: true
  severity: style
